import {
  pgTable,
  uuid,
  text,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
  real,
  boolean,
  customType,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

const vector = customType<{ data: number[]; driverData: string }>({
  dataType() {
    return "vector(768)";
  },
  toDriver(value: number[]) {
    return `[${value.join(",")}]`;
  },
  fromDriver(value: string) {
    return JSON.parse(value);
  },
});

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  firebaseUid: text("firebase_uid").notNull().unique(),
  apiToken: text("api_token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const knowledgeNodes = pgTable(
  "knowledge_nodes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    slug: text("slug"),
    type: text("type").notNull(),
    title: text("title").notNull(),
    content: text("content").notNull(),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    source: text("source"),
    sourceMeta: jsonb("source_meta").$type<Record<string, unknown>>().default({}),
    embedding: vector("embedding"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("knowledge_nodes_user_id_idx").on(table.userId),
    index("knowledge_nodes_type_idx").on(table.userId, table.type),
    index("knowledge_nodes_source_idx").on(table.userId, table.source),
    uniqueIndex("knowledge_nodes_user_slug_idx").on(table.userId, table.slug),
  ]
);

export const knowledgeEdges = pgTable(
  "knowledge_edges",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => knowledgeNodes.id, { onDelete: "cascade" }),
    targetId: uuid("target_id")
      .notNull()
      .references(() => knowledgeNodes.id, { onDelete: "cascade" }),
    relationship: text("relationship").notNull(),
    weight: real("weight").notNull().default(1.0),
    autoGenerated: boolean("auto_generated").notNull().default(false),
    lastAnalyzedAt: timestamp("last_analyzed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("knowledge_edges_source_idx").on(table.sourceId),
    index("knowledge_edges_target_idx").on(table.targetId),
    uniqueIndex("knowledge_edges_unique_idx").on(
      table.sourceId,
      table.targetId,
      table.relationship
    ),
  ]
);

// ─── OAuth ───────────────────────────────────────────────

export const oauthClients = pgTable("oauth_clients", {
  id: uuid("id").defaultRandom().primaryKey(),
  clientId: text("client_id").notNull().unique(),
  clientSecret: text("client_secret"),
  clientSecretExpiresAt: timestamp("client_secret_expires_at", { withTimezone: true }),
  redirectUris: text("redirect_uris")
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),
  clientName: text("client_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const oauthCodes = pgTable("oauth_codes", {
  id: uuid("id").defaultRandom().primaryKey(),
  code: text("code").notNull().unique(),
  clientId: text("client_id").notNull(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  redirectUri: text("redirect_uri").notNull(),
  codeChallenge: text("code_challenge").notNull(),
  codeChallengeMethod: text("code_challenge_method").notNull().default("S256"),
  scopes: text("scopes")
    .array()
    .notNull()
    .default(sql`'{"read","write"}'::text[]`),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  used: boolean("used").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ─── Dream Cycle ────────────────────────────────────────

export const dreamSuggestions = pgTable("dream_suggestions", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  type: text("type").notNull(), // "edge_suggestion" | "contradiction" | "orphan"
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
  status: text("status").notNull().default("pending"), // "pending" | "accepted" | "dismissed"
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ─── Types ───────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type KnowledgeNode = typeof knowledgeNodes.$inferSelect;
export type NewKnowledgeNode = typeof knowledgeNodes.$inferInsert;
export type KnowledgeEdge = typeof knowledgeEdges.$inferSelect;
export type NewKnowledgeEdge = typeof knowledgeEdges.$inferInsert;
export type DreamSuggestion = typeof dreamSuggestions.$inferSelect;
export type NewDreamSuggestion = typeof dreamSuggestions.$inferInsert;
