import { eq, and } from "drizzle-orm";
import { db } from "@/lib/db";
import { knowledgeEdges } from "@/lib/db/schema";
import { getNodeBySlug, createEdge } from "@/lib/db/queries";
import { parseWikilinks } from "./wikilinks";
import { generateSlug } from "@/lib/utils/slugify";

export interface SyncResult {
  created: number;
  removed: number;
  unresolved: string[];
}

export async function syncWikilinkEdges(
  workspaceId: string,
  nodeId: string,
  content: string
): Promise<SyncResult> {
  const wikilinks = parseWikilinks(content);

  // Remove old auto-generated edges from this node within this workspace
  await db
    .delete(knowledgeEdges)
    .where(
      and(
        eq(knowledgeEdges.workspaceId, workspaceId),
        eq(knowledgeEdges.sourceId, nodeId),
        eq(knowledgeEdges.autoGenerated, true)
      )
    );

  let created = 0;
  const unresolved: string[] = [];

  for (const link of wikilinks) {
    const slug = generateSlug(link.target);
    const targetNode = await getNodeBySlug(slug, workspaceId);

    if (!targetNode || targetNode.id === nodeId) {
      if (!targetNode) unresolved.push(link.target);
      continue;
    }

    const edge = await createEdge({
      workspaceId,
      sourceId: nodeId,
      targetId: targetNode.id,
      relationship: link.relationship,
      autoGenerated: true,
    });

    if (edge) created++;
  }

  return { created, removed: 0, unresolved };
}
